# Generated by Django 5.2.3 on 2025-07-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('biografia', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instructores/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
