# Generated by Django 5.2.3 on 2025-07-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='foto',
            field=models.ImageField(default='/avatars/default.png', upload_to='instructores/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(default='/avatars/default.png', upload_to='avatars/'),
        ),
    ]
