# Generated by Django 5.2.3 on 2025-07-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HashiDojo', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
    ]
